#pragma once

#include <atomic>
#include <chrono>
#include <list>
#include <memory>

#include <driver/gpio.h>
#include <esp_sleep.h>

#ifdef CONFIG_ULP_COPROC_ENABLED
#include <driver/rtc_io.h>
#if defined(CONFIG_ULP_COPROC_TYPE_RISCV)
#include <ulp_riscv.h>
#elif defined(CONFIG_ULP_COPROC_TYPE_LP_CORE)
#include <ulp_lp_core.h>
#endif
// Generated by the ULP build system from ulp/pulse_counter.c.
// Declares ulp_channel_count, ulp_gpio_num[], ulp_debounce_cycles[], ulp_pulse_count[].
#include "ulp_pulse_counter.h"
// Embedded ULP binary produced by CMake.
extern const uint8_t ulp_pulse_counter_bin_start[] asm("_binary_ulp_pulse_counter_bin_start");
extern const uint8_t ulp_pulse_counter_bin_end[]   asm("_binary_ulp_pulse_counter_bin_end");
#endif

#include <Concurrent.hpp>
#include <EspException.hpp>
#include <Log.hpp>
#include <Pin.hpp>
#include <PowerManager.hpp>

using namespace std::chrono;

namespace farmhub::kernel {

LOGGING_TAG(PULSE, "pulse")

class PulseCounterManager;

struct PulseCounterConfig {
    InternalPinPtr pin;
    /**
     * @brief Ignore any pulses that happen within this time after the previous pulse.
     */
    microseconds debounceTime = 0us;
};

/**
 * @brief Abstract interface for pulse counters.
 *
 * Created via PulseCounterManager::create(), which selects the appropriate implementation:
 * - UlpPulseCounter for RTC-capable GPIOs (GPIO 0–21 on ESP32-S3): counts via the ULP-RISC-V
 *   coprocessor, requiring no CPU wakeups during light sleep.
 * - GpioPulseCounter for all other GPIOs: counts via GPIO interrupts, light-sleep aware.
 */
class PulseCounter {
public:
    virtual uint32_t getCount() const = 0;
    virtual uint32_t reset() = 0;
    virtual PinPtr getPin() const = 0;
    virtual ~PulseCounter() = default;

protected:
    PulseCounter() = default;
};

// ============================================================================
// UlpPulseCounter — RTC/LP GPIO path, no per-pulse CPU wakeups
// ============================================================================

#ifdef CONFIG_ULP_COPROC_ENABLED

/**
 * @brief Pulse counter backed by the ULP/LP-core coprocessor.
 *
 * The coprocessor polls the GPIO continuously regardless of main CPU sleep state:
 * - ESP32-S3 (ULP-RISC-V): ~8 MHz polling rate; requires an RTC-capable GPIO (GPIO 0–21).
 * - ESP32-C6 (LP Core): ~16 MHz polling rate; requires an LP-capable GPIO (GPIO 0–7).
 *
 * The main CPU reads the monotonically increasing counter from RTC slow memory and
 * computes the delta since the last read. No wakeup sources are registered per pulse.
 *
 * PulseCounterManager::start() must be called after all channels are created.
 *
 * See docs/ULP-PulseCounter.md for full design rationale.
 */
class UlpPulseCounter final : public PulseCounter {
public:
    uint32_t getCount() const override {
        uint32_t current = ulp_pulse_count[channelIndex];
        uint32_t delta = current - lastSeen;
        LOGTV(PULSE, "Counted %" PRIu32 " ULP pulses on pin %s",
            delta, pin->getName().c_str());
        return delta;
    }

    uint32_t reset() override {
        uint32_t current = ulp_pulse_count[channelIndex];
        uint32_t delta = current - lastSeen;
        lastSeen = current;
        LOGTV(PULSE, "Counted %" PRIu32 " ULP pulses and cleared on pin %s",
            delta, pin->getName().c_str());
        return delta;
    }

    PinPtr getPin() const override {
        return pin;
    }

private:
    UlpPulseCounter(InternalPinPtr pin, uint32_t channelIndex)
        : pin(std::move(pin))
        , channelIndex(channelIndex)
        , lastSeen(0) {
    }

    const InternalPinPtr pin;
    const uint32_t channelIndex;
    uint32_t lastSeen;

    friend class PulseCounterManager;
};

#endif    // CONFIG_ULP_COPROC_ENABLED

// ============================================================================
// GpioPulseCounter — GPIO interrupt path, light-sleep aware
// ============================================================================

class GpioPulseCounter;
static void handleGpioPulseCounterInterrupt(void* arg);

/**
 * @brief Counts pulses on a GPIO pin using interrupts.
 *
 * Note: This counter is safe to use with the device entering and exiting light sleep.
 *
 * When the device is awake, it watches for edges, and counts falling edges.
 * When the device enters light sleep, we set up an interrupt to wake on level change.
 * This is necessary because in light sleep the device cannot detect edges, only levels.
 *
 * Use this for GPIOs that are not RTC-capable. For RTC-capable GPIOs, prefer
 * UlpPulseCounter (selected automatically by PulseCounterManager).
 */
class GpioPulseCounter final : public PulseCounter {
public:
    GpioPulseCounter(const InternalPinPtr& pin, microseconds debounceTime)
        : pin(pin)
        , debounceTime(debounceTime)
        , lastEdge(pin->digitalRead())
        , lastCountedEdgeTime(steady_clock::now()) {
        auto gpio = pin->getGpio();

        // Configure the GPIO pin as an input
        gpio_config_t config = {
            .pin_bit_mask = 1ULL << gpio,
            .mode = GPIO_MODE_INPUT,
            .pull_up_en = GPIO_PULLUP_DISABLE,
            .pull_down_en = GPIO_PULLDOWN_ENABLE,
            .intr_type = GPIO_INTR_ANYEDGE,
        };
        ESP_ERROR_THROW(gpio_config(&config));

        // Use the same configuration while in light sleep
        ESP_ERROR_THROW(gpio_sleep_sel_dis(gpio));

        // TODO Where should this be called?
        ESP_ERROR_THROW(esp_sleep_enable_gpio_wakeup());

        LOGTD(PULSE, "Registered interrupt-based pulse counter on pin %s",
            pin->getName().c_str());
    }

    uint32_t getCount() const override {
        uint32_t count = edgeCount.load();
        LOGTV(PULSE, "Counted %" PRIu32 " pulses on pin %s",
            count, pin->getName().c_str());
        return count;
    }

    uint32_t reset() override {
        uint32_t count = edgeCount.exchange(0);
        LOGTV(PULSE, "Counted %" PRIu32 " pulses and cleared on pin %s",
            count, pin->getName().c_str());
        return count;
    }

    PinPtr getPin() const override {
        return pin;
    }

private:
    void handleGoingToLightSleep() {
        auto currentState = pin->digitalRead();
        // Make sure we wake up again to check for the opposing edge
        ESP_ERROR_CHECK(gpio_wakeup_enable(
            pin->getGpio(),
            currentState == 0
                ? GPIO_INTR_HIGH_LEVEL
                : GPIO_INTR_LOW_LEVEL));
    }

    void handleWakingUpFromLightSleep() {
        // Switch back to edge detection when we are awake
        ESP_ERROR_CHECK(gpio_wakeup_disable(pin->getGpio()));
        ESP_ERROR_CHECK(gpio_set_intr_type(pin->getGpio(), GPIO_INTR_ANYEDGE));
        handleGpioPulseCounterInterrupt(this);
    }

    const InternalPinPtr pin;
    const microseconds debounceTime;
    std::atomic<uint32_t> edgeCount { 0 };
    int lastEdge;
    steady_clock::time_point lastCountedEdgeTime;

    friend void handleGpioPulseCounterInterrupt(void* arg);
    friend class PulseCounterManager;
};

static void IRAM_ATTR handleGpioPulseCounterInterrupt(void* arg) {
    auto* counter = static_cast<GpioPulseCounter*>(arg);
    auto currentState = counter->pin->digitalReadFromISR();
    if (currentState != counter->lastEdge) {
        counter->lastEdge = currentState;

        // Software debounce: ignore edges that happen too quickly
        if (counter->debounceTime > 0us) {
            auto now = steady_clock::now();
            auto timeSinceLastEdge = duration_cast<microseconds>(now - counter->lastCountedEdgeTime);
            if (timeSinceLastEdge < counter->debounceTime) {
                return;
            }
            counter->lastCountedEdgeTime = now;
        }

        if (currentState == 0) {
            counter->edgeCount++;
        }
    }
}

// ============================================================================
// PulseCounterManager
// ============================================================================

/**
 * @brief Creates and manages pulse counters, automatically selecting the implementation.
 *
 * For RTC/LP-capable GPIOs: creates a UlpPulseCounter (coprocessor-based, zero CPU wakeups).
 *   - ESP32-S3: GPIO 0–21 (ULP-RISC-V, ~8 MHz)
 *   - ESP32-C6: GPIO 0–7  (LP Core, ~16 MHz)
 * For all other GPIOs: creates a GpioPulseCounter (interrupt-based, light-sleep aware).
 *
 * Call start() after all counters have been created to load and start the coprocessor firmware.
 * start() is a no-op if no ULP counters were created.
 */
class PulseCounterManager {
public:
    std::shared_ptr<PulseCounter> create(const PulseCounterConfig& config) {
        auto gpio = config.pin->getGpio();

#ifdef CONFIG_ULP_COPROC_ENABLED
        if (rtc_gpio_is_valid_gpio(gpio)) {
            return createUlp(config);
        }
#endif
        return createGpio(config);
    }

    /**
     * @brief Load and start the ULP/LP-core firmware.
     *
     * Must be called after all ULP channels are registered (i.e., after all create() calls
     * for RTC/LP-capable GPIOs). Safe to call even if no ULP channels were created (no-op).
     * Calling more than once is also a no-op.
     */
    void start() {
#ifdef CONFIG_ULP_COPROC_ENABLED
        if (ulpStarted || ulpNextChannel == 0) {
            return;
        }
        ulpStarted = true;

        ulp_channel_count = ulpNextChannel;

        size_t size = ulp_pulse_counter_bin_end - ulp_pulse_counter_bin_start;
#if defined(CONFIG_ULP_COPROC_TYPE_RISCV)
        ESP_ERROR_THROW(ulp_riscv_load_binary(ulp_pulse_counter_bin_start, size));
        ESP_ERROR_THROW(ulp_riscv_run());
#elif defined(CONFIG_ULP_COPROC_TYPE_LP_CORE)
        ESP_ERROR_THROW(ulp_lp_core_load_binary(ulp_pulse_counter_bin_start, size));
        ulp_lp_core_cfg_t cfg = {
            .wakeup_source = ULP_LP_CORE_WAKEUP_SOURCE_HP_CPU,
        };
        ESP_ERROR_THROW(ulp_lp_core_run(&cfg));
#endif

        LOGTD(PULSE, "ULP pulse counter started with %" PRIu32 " channel(s)", ulpNextChannel);
#endif
    }

private:
    // GPIO interrupt path
    bool gpioInitialized = false;
    std::list<GpioPulseCounter*> gpioCounters;

    std::list<std::shared_ptr<PulseCounter>> ulpCounters;

#ifdef CONFIG_ULP_COPROC_ENABLED
    static constexpr uint32_t ULP_MAX_CHANNELS = 4;

    // ULP/LP-core path
    bool ulpStarted = false;
    uint32_t ulpNextChannel = 0;

    std::shared_ptr<PulseCounter> createUlp(const PulseCounterConfig& config) {
        if (ulpNextChannel >= ULP_MAX_CHANNELS) {
            throw std::runtime_error("PulseCounterManager: ULP channel limit exceeded");
        }

        auto gpio = config.pin->getGpio();

        // Route pin to RTC/LP domain with pull-down.
        ESP_ERROR_THROW(rtc_gpio_init(gpio));
        ESP_ERROR_THROW(rtc_gpio_set_direction(gpio, RTC_GPIO_MODE_INPUT_ONLY));
        ESP_ERROR_THROW(rtc_gpio_pulldown_en(gpio));
        ESP_ERROR_THROW(rtc_gpio_pullup_dis(gpio));

        uint32_t index = ulpNextChannel++;

        uint32_t debounceUs = static_cast<uint32_t>(config.debounceTime.count());
        ulp_gpio_num[index]    = static_cast<uint32_t>(gpio);
        ulp_debounce_us[index] = debounceUs;
        ulp_pulse_count[index] = 0;

        LOGTD(PULSE, "Registered ULP pulse counter on pin %s (channel %" PRIu32 ", debounce %" PRIu32 " us)",
            config.pin->getName().c_str(), index, debounceUs);

        auto ulpCounter = std::shared_ptr<UlpPulseCounter>(new UlpPulseCounter(config.pin, index));
        ulpCounters.push_back(ulpCounter);
        return ulpCounter;
    }
#endif    // CONFIG_ULP_COPROC_ENABLED

    std::shared_ptr<PulseCounter> createGpio(const PulseCounterConfig& config) {
        if (!gpioInitialized) {
            gpioInitialized = true;

            // Make sure we handle any state changes when the device wakes up due to a GPIO interrupt
            esp_pm_sleep_cbs_register_config_t sleepCallbackConfig = {
                .enter_cb = [](int64_t /*timeToSleepInUs*/, void* arg) {
                    auto* self = static_cast<PulseCounterManager*>(arg);
                    for (auto* counter : self->gpioCounters) {
                        counter->handleGoingToLightSleep();
                    }
                    return ESP_OK; },
                .exit_cb = [](int64_t /*timeSleptInUs*/, void* arg) {
                    auto* self = static_cast<PulseCounterManager*>(arg);
                    for (auto* counter : self->gpioCounters) {
                        counter->handleWakingUpFromLightSleep();
                    }
                    return ESP_OK; },
                .enter_cb_user_arg = this,
                .exit_cb_user_arg = this,
                .enter_cb_prior = 0,
                .exit_cb_prior = 0,
            };
            ESP_ERROR_THROW(esp_pm_light_sleep_register_cbs(&sleepCallbackConfig));
        }

        auto counter = std::make_shared<GpioPulseCounter>(config.pin, config.debounceTime);

        // Attach the ISR handler to the GPIO pin
        ESP_ERROR_THROW(gpio_isr_handler_add(config.pin->getGpio(), handleGpioPulseCounterInterrupt, counter.get()));

        // Keep the counter alive in the manager
        gpioCounters.push_back(counter.get());
        ulpCounters.push_back(counter);
        return counter;
    }
};

}    // namespace farmhub::kernel
